# -*- coding: utf-8 -*-
"""churn_classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rLp00OkaXvZ9K9XcDvXkWx_kItaovyGA
"""

"""
Customer Churn Classification Module
------------------------------------
Algorithms:
1. Naive Bayes
2. Decision Tree
3. Random Forest

Author: Classification Owner
"""

import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    confusion_matrix,
    classification_report
)

# ---------------------------------------
# Load Dataset
# ---------------------------------------

def load_data(path="/content/Churn_Modelling.csv"):
    return pd.read_csv(path)


# ---------------------------------------
# Preprocess Dataset
# ---------------------------------------

def preprocess_data(df):

    df = df.drop(
        ["RowNumber", "CustomerId", "Surname"],
        axis=1
    )

    encoder = LabelEncoder()
    df["Gender"] = encoder.fit_transform(df["Gender"])

    df = pd.get_dummies(
        df,
        columns=["Geography"],
        drop_first=True
    )

    X = df.drop("Exited", axis=1)
    y = df["Exited"]

    return X, y


# ---------------------------------------
# Train/Test Split + Scaling
# ---------------------------------------

def split_and_scale(X, y):

    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.20,
        random_state=42
    )

    scaler = StandardScaler()

    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)

    return X_train, X_test, y_train, y_test, scaler


# ---------------------------------------
# Train Models
# ---------------------------------------

def train_models(X_train, y_train):

    models = {
        "Naive Bayes": GaussianNB(),

        "Decision Tree": DecisionTreeClassifier(
            random_state=42
        ),

        "Random Forest": RandomForestClassifier(
            n_estimators=100,
            random_state=42
        )
    }

    for model in models.values():
        model.fit(X_train, y_train)

    return models


# ---------------------------------------
# Evaluate Models
# ---------------------------------------

def evaluate_models(models, X_test, y_test):

    results = {}

    for name, model in models.items():

        prediction = model.predict(X_test)

        results[name] = {

            "accuracy": round(
                accuracy_score(y_test, prediction) * 100,
                2
            ),

            "confusion_matrix":
                confusion_matrix(
                    y_test,
                    prediction
                ).tolist(),

            "classification_report":
                classification_report(
                    y_test,
                    prediction,
                    output_dict=True
                )
        }

    return results


# ---------------------------------------
# Best Model
# ---------------------------------------

def get_best_model(models, results):

    best_name = max(
        results,
        key=lambda x: results[x]["accuracy"]
    )

    return best_name, models[best_name]


# ---------------------------------------
# Predict One Customer
# ---------------------------------------

def predict_customer(model, scaler, customer_df):

    customer_scaled = scaler.transform(customer_df)

    prediction = model.predict(customer_scaled)

    if prediction[0] == 1:
        return "Customer is likely to Churn"

    return "Customer is likely to Stay"


# ---------------------------------------
# Main Pipeline
# ---------------------------------------

def run_classification():

    df = load_data()

    X, y = preprocess_data(df)

    X_train, X_test, y_train, y_test, scaler = split_and_scale(
        X,
        y
    )

    models = train_models(
        X_train,
        y_train
    )

    results = evaluate_models(
        models,
        X_test,
        y_test
    )

    best_model_name, best_model = get_best_model(
        models,
        results
    )

    comparison = pd.DataFrame({
        "Model": list(results.keys()),
        "Accuracy (%)": [
            results[m]["accuracy"]
            for m in results
        ]
    })

    return {
        "results": results,
        "comparison": comparison,
        "best_model_name": best_model_name,
        "best_model": best_model,
        "scaler": scaler,
        "X_test": X_test,
        "y_test": y_test
    }


# ---------------------------------------
# Standalone Execution
# ---------------------------------------

if __name__ == "__main__":

    output = run_classification()

    print("\n========== MODEL COMPARISON ==========\n")

    print(output["comparison"])

    print("\nBest Model:", output["best_model_name"])

    print("\n======================================")

    for model_name, metrics in output["results"].items():

        print(f"\n{model_name}")
        print("-" * 40)

        print(f"Accuracy : {metrics['accuracy']}%")

        print("\nConfusion Matrix")
        print(metrics["confusion_matrix"])

        print("\nClassification Report")

        report = pd.DataFrame(
            metrics["classification_report"]
        ).transpose()

        print(report)